In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
MISSING = -9999

In [3]:
df_train = pd.read_csv("../data/interim/train.csv")
df_test = pd.read_csv("../data/interim/test.csv")

/Users/tingwei758/opt/anaconda3/envs/kaggle/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (3,4,6,10,12,18,24,35,56,57,65,85,86,87,88,89,98,99,100,105,124,125,126,127,128,130,131,133,166,171,172,192,193,194,195,204,205,206,207,228,229,230,240,256,257,258,259,260,261,262) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/tingwei758/opt/anaconda3/envs/kaggle/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (3,6,10,12,21,24,35,85,87,88,89,100,124,126,127,128,130,131,133,166,172,177,193,194,195,205,206,207,220,222,228,229,230,240,257,258,260,261,262) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
categorical = ['v17', 'v20', 'v25', 'v78', 'v154', 'v155', 'v161', 'cntry']

yes_no_cols = ['v6', 'v7', 'v8', 'v9', 'v10', 'v11', 'v14', 'v18', 'v21', 'v22', 'v23',
       'v24', 'v43', 'v53', 'v77', 'v105', 'v108', 'v152', 'v157', 'v162',
       'v165', 'v172', 'v173', 'v187', 'v188', 'v221', 'v241', 'v242', 'v243',
       'v248', 'v254', 'v256', 'v257']

In [5]:
df_train["test"] = 0
df_test["test"] = 1

In [6]:
df = pd.concat([df_train, df_test]).reset_index(drop=True)

/Users/tingwei758/opt/anaconda3/envs/kaggle/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [7]:
df.shape

(39325, 274)

In [8]:
df.apply(pd.to_numeric, args=('coerce',)).count().loc['v17']

35165

In [9]:
k = df.apply(pd.to_numeric, args=('coerce',)).count().sort_values()

In [10]:
print(k.to_string())

cntry            0
v262             1
v207             1
v89              1
v195             1
v20              3
v88              9
v261             9
v194            10
v206            10
v260            23
v87             26
v193            27
v205            27
v259            43
v86             45
v204            46
v192            46
v270            67
v97             69
v215            72
v203            72
v269           163
v96            168
v202           169
v214           169
v154           301
v268           443
v95            458
v213           461
v201           461
v267          1289
v94           1320
v200          1327
v212          1327
v164          2354
v123          2965
v266          3661
v93           3723
v199          3724
v211          3724
v69           4051
v191          4185
v153          4387
v158          5354
v23           9009
v265         10107
v92          10186
v210         10215
v198         10215
v168         10551
v241         11064
v243         11068
v5           12117
v252         13642
v174         13975
v151         13986
v71          14244
v188         16603
v264         17056
v91          17262
v209         17289
v197         17289
v173         17887
v182         18481
v22          18679
v160         19926
v63          21817
v62          21817
v68          21817
v190         22490
v170         22593
v216         23076
v11          25115
satisfied    30080
v263         30635
v196         30934
v208         30934
v90          30965
v104         31223
v255         31637
v78          32931
v161         33171
v250         33345
v155         33470
v169         33530
v66          33653
v59          33653
v58          33653
v157         34146
v251         34284
v156         35083
v61          35108
v60          35108
v67          35108
v17          35165
v75          35203
v167         35490
v135         35624
v150         35703
v249         35814
v231         35829
v76          35875
v70          36050
v152         36065
v232         36093
v254         36104
v108         36121
v238         36181
v239         37172
v25          37607
v225         37676
v132         37751
v121         37839
v109         37962
v130         37989
v131         37989
v126         37995
v127         37995
v120         38004
v256         38034
v147         38063
v140         38117
v111         38128
v145         38133
v148         38170
v226         38171
v223         38172
v83          38172
v137         38208
v146         38231
v149         38234
v144         38234
v72          38236
v115         38237
v118         38240
v136         38248
v141         38257
v138         38258
v112         38270
v139         38279
v114         38281
v110         38284
v117         38285
v113         38287
v143         38289
v142         38305
v116         38312
v119         38340
v184         38386
v183         38442
v14          38515
v103         38532
v102         38532
v236         38534
v233         38588
v1           38612
v237         38624
v84          38632
v19          38666
v224         38690
v73          38739
v220         38753
v219         38760
v9           38810
v181         38817
v235         38825
v159         38924
v2           38929
v101         38956
v253         38960
v64          38976
v122         38987
v162         38988
v43          38989
v74          38997
v248         39002
v13          39028
v227         39038
v228         39039
v234         39040
v189         39042
v230         39043
v229         39043
v178         39054
v53          39066
v4           39075
v82          39082
v77          39084
v81          39084
v6           39087
v80          39109
v79          39120
v166         39143
v8           39145
v187         39148
v222         39150
v242         39157
v98          39157
v186         39166
v221         39177
v171         39177
v163         39185
v179         39185
v65          39188
v57          39188
v56          39188
v177         39218
v100         39224
v21          39226
v258         39228
v3           39228
v165         39234
v35          39237
v7           39237
v105         39238
v18          39243
v180         39250
v257         39250
v172         39252
v240         39254
v99          39278
v24          39303
v85          39304
v10          39315
v124         39315
v128         39318
v133         39318
v12          39320
v125         39322
v52          39325
v245         39325
v244         39325
v217         39325
v185         39325
v176         39325
v175         39325
v134         39325
v15          39325
v246         39325
v129         39325
v107         39325
v106         39325
test         39325
id           39325
v16          39325
v247         39325
v26          39325
v27          39325
v50          39325
v54          39325
v55          39325
v49          39325
v48          39325
v47          39325
v46          39325
v45          39325
v44          39325
v42          39325
v41          39325
v40          39325
v39          39325
v38          39325
v37          39325
v36          39325
v34          39325
v33          39325
v32          39325
v31          39325
v30          39325
v29          39325
v28          39325
v51          39325
v218         39325

In [10]:
df = df.drop(columns=list(set(k[k < 200].index).difference(categorical)))

In [11]:
df.shape

(39325, 250)

In [12]:
df[yes_no_cols] = df[yes_no_cols].replace(to_replace=["2", 2], value=0)
df[yes_no_cols] = df[yes_no_cols].replace(to_replace=["1", 1], value=1)

In [13]:
one_hot = categorical + ['v70', 'v71', 'v72', 'v73', 'v102', 'v103', 
                           'v158', 'v159', 'v160', 'v163', 'v164', 
                           'v169', 'v170', 'v190', 'v191',
                          'v216', 'v231']

In [14]:
numeric = [col for col in df.columns if col not in one_hot + ['id', 'satisfied']]

In [15]:
# for col in numeric:
#     numeric_col = pd.to_numeric(df[col], errors='coerce')
#     na_indicator = numeric_col.isna()
#     if sum(na_indicator) > 0:
#         df[col+'_ind'] = (~na_indicator).astype(int)
#         df[col+'_missing'] = np.where(na_indicator, df[col], np.nan)
#     df[col] = numeric_col

In [16]:
# missing = [col for col in df.columns if col.endswith('_missing')]

In [17]:
for col in one_hot:
    df[col] = pd.Categorical(df[col])
df_encoded = pd.get_dummies(df, columns=one_hot, drop_first=True)

In [18]:
df['cntry'].value_counts()

DE    2965
IL    2509
IE    2332
GB    2215
LT    2208
CZ    2097
FI    2048
EE    2002
ES    1884
NL    1873
FR    1870
SE    1767
AT    1763
BE    1736
HU    1662
PL    1579
CH    1500
DK    1473
NO    1400
PT    1247
SI    1195
Name: cntry, dtype: int64

In [19]:
len(df)

39325

In [20]:
df_encoded = df_encoded.apply(pd.to_numeric, args=('coerce',)).fillna(MISSING)

In [21]:
df_encoded.to_csv("../data/processed/data_encoded.csv", index=False)

In [22]:
df_encoded

,id,satisfied,test,v1,v10,v100,v101,v104,v105,v106,...,v216_6,v231_.b,v231_.c,v231_.d,v231_1,v231_2,v231_3,v231_4,v231_5,v231_6
0,9948,0.0,0,2.0,1.0,1.0,2.0,2.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
1,25601,0.0,0,4.0,1.0,1.0,2.0,2.0,3.0,0,...,0,0,0,0,0,0,0,1,0,0
2,8592,1.0,0,6.0,1.0,4.0,2.0,1.0,3.0,0,...,0,0,0,0,0,0,0,1,0,0
3,29593,0.0,0,10.0,1.0,1.0,2.0,2.0,3.0,1,...,0,0,0,0,0,0,0,1,0,0
4,4252,1.0,0,0.0,1.0,1.0,1.0,3.0,3.0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39320,31430,-9999.0,1,0.0,1.0,4.0,1.0,5.0,3.0,1,...,0,0,0,0,0,0,0,1,0,0
39321,3876,-9999.0,1,1.0,1.0,2.0,2.0,-9999.0,3.0,1,...,0,0,0,0,0,0,0,1,0,0
39322,20710,-9999.0,1,5.0,1.0,4.0,2.0,7.0,3.0,0,...,0,0,0,0,0,0,1,0,0,0
39323,26015,-9999.0,1,8.0,1.0,3.0,2.0,5.0,3.0,0,...,0,0,0,0,0,0,0,1,0,0
39324,12970,-9999.0,1,5.0,1.0,2.0,2.0,2.0,1.0,0,...,0,0,0,0,0,0,0,1,0,0

In [23]:
# df_numeric = df.apply(pd.to_numeric, args=('coerce',)).fillna(MISSING)

In [24]:
# df_numeric.to_csv("../data/processed/data_encoded.csv", index=False)